---
# Libro de jugadas de Ansible para instalación del servidor web Snipe-IT en una máquina EC2 en AWS
- name: "snipeitweb"
  hosts: all
  become: yes

  tasks:
  - name: Instalar paquete zip necesario para gestionar las copias de seguridad de Snipe-IT
    apt:
      name: zip 
      state: present

  - name: Instalar aws cli necesario para interactuar con los recursos de AWS
    apt:
      name: awscli 
      state: present

  - name: Traemos la copia de seguridad de Snipe-IT desde Amazon S3
    command: aws s3 cp s3://terraform-jenkins-dev/snipeit/snipeit.zip /home/ubuntu/snipeit.zip
    args:
      creates: /home/ubuntu/snipeit.zip

  - name: Traemos el fichero de entorno desde Amazon S3
    command: aws s3 cp s3://terraform-jenkins-dev/snipeit/.envsite /home/ubuntu/.envsite
    args:
      creates: /home/ubuntu/.envsite
      
  - name: Traemos el fichero de configuración del servidor web desde Amazon S3
    command: aws s3 cp s3://terraform-jenkins-dev/snipeit/site.conf /home/ubuntu/site.conf 
    args:
      creates: /home/ubuntu/site.conf   

  - name: Instalar el paquete composer mediante el cual instalaremos las dependencias de librerias de Snipe-IT
    apt:
      name: composer
      state: present
   
  - name: Instalar las extensiones PHP requeridas
    apt:
      name:
        - php7.2-fpm
        - php7.2-common
        - php7.2-gmp
        - php7.2-intl
        - php7.2-xmlrpc
        - php7.2-cli
        - php7.2-gd
        - php7.2-mbstring
        - php7.2-tokenizer
        - php7.2-curl
        - php7.2-mysql
        - php7.2-ldap
        - php7.2-zip
        - php7.2-fileinfo
        - php7.2-bcmath
        - php7.2-xml
      state: present

  - name: Instalar las librerias y paquetes a través de composer
    composer:
      command: install
      working_dir: ~/snipeit
    become: no
    become_user: ubuntu    

  - name: Instalar motor de base de datos aunque en este servidor usaremos la parte de cliente
    apt:
      name: mysql-server    
      state: present

  - name: Instalar el servidor web Nginx
    apt:
      name: nginx
      state: present

  - name: Añadir el usuario del sistema al grupo web
    user:
      name: ubuntu
      group: www-data

  - name: Configurar el servidor web con el fichero extraido de Amazon S3
    copy:
      src: /home/ubuntu/site.conf 
      dest: /etc/nginx/sites-available/default
      mode: u+rw
    
  - name: Crear el enlace simbólico entre los sitios web disponibles y activos de Nginx
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
      
  - name: Establecer el entorno de la aplicación con la restauración del fichero de entorno almacenado en Amazon S3
    copy:
      src: /home/ubuntu/.envsite
      dest: ~/snipeit/.env
      mode: u+rw
    become: no
    become_user: ubuntu
    
  - name: Mover directorio de Snipe-IT a la carpeta de servicio web cuando no existe el fichero de entorno y registrar el estado de este paso como fresh.
    command: mv /home/ubuntu/snipeit /var/www/snipeit
    args:
      creates: /var/www/snipeit/.env
    register: fresh

  - name: Escribir la clave para desencriptar la base de datos en el fichero de entorno de Snipe-IT suministrada mediante variable de entorno la primera vez que se ejecute el libro.
    lineinfile:
      path: /var/www/snipeit/.env
      regexp: '^APP_KEY=ChangeMe'
      line: APP_KEY=base64:{{ appkey }}
    when: fresh.changed

  - name: Escribir la clave de base de datos suministrada mediante variable de entorno.
    lineinfile:
      path: /var/www/snipeit/.env
      regexp: '^DB_PASSWORD=ChangeMe'
      line: DB_PASSWORD={{ mysqlpassword }}
    when: fresh.changed

  - name: Extracción de la copia de seguridad de Snipe-IT. Se extraerá en la ruta del servidor web.
    unarchive:
      src: /home/ubuntu/snipeit.zip
      dest: /

  - name: Cambiar el propietario de la carpeta del servidor web
    file:
      path: /var/www/snipeit
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: Cambiar el propietario de la carpeta pública de carga de datos al usuario de sistema
    file:
      path: /var/www/snipeit/public/uploads
      state: directory
      recurse: yes
      owner: ubuntu
         
  - name: Cambiar el propietario de la carpeta pública de almacenamiento auxiliar al usuario de sistema
    file:
      path: /var/www/snipeit/storage
      state: directory
      recurse: yes
      owner: ubuntu
    
  - name: Reiniciar servidor web Nginx
    service:
      name: nginx
      state: restarted
      
  - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
    cron:
      name: "backup snipeit en S3"
      minute: "0"
      hour: "2"
      job: "cd /var/www/snipeit/ && php artisan snipeit:backup -n && aws s3 cp /var/www/snipeit/storage/app/backups/snipe* s3://terraform-jenkins-dev/snipeit/ && rm /var/www/snipeit/storage/app/backups/snipe*"
      
  - name: Mostrar 
    debug:
      msg: "La clave de encriptación es base64:{{ appkey }} y la contraseña de la base de datos es {{ mysqlpassword }}"
